version: '3.4'

services:
  dotnet-watch-docker-example:
    container_name: dotnet_watch_docker_example
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
    ports:
      - 5001:5001
    volumes:
      - ./api:/app
    working_dir: /app
    command: dotnet watch run




    services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: backend
  #   env_file:
  #     - backend/.env
  #   volumes:
  #     - .:/usr/src/app/backend
  #   command: sh -c "cd backend && npm run start:dev"
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  # widgets:
  #   build:
  #     dockerfile: Dockerfile
  #     context: widgets
  #   volumes:
  #     - .:/usr/src/app/widgets
  #   command: sh -c "cd widgets && npm run dev"
  #   ports:
  #     - 8001:8001
  #   depends_on:
  #     - postgres
volumes:
  postgres: